---

- hosts: rancher
  remote_user: root

  tasks:

  - name: install rancher
    shell: docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher 
    notify:
    - install rancher done

  handlers:
  - name: install rancher done
    shell: echo "install rancher done...ok"

