---
- hosts: localhost
  remote_user: zx
  vars:
    DOMAIN:

  tasks:
    - name: check param
      shell: |
            if [ -z {{DOMAIN}} ];then
                echo "需要DOMAIN参数"
                exit 1
            else
                :
            fi

    - name: install httpd
      shell: echo "task {{DOMAIN}}"
      notify:
        - restart httpd

  handlers:
    - name: restart httpd
      shell: echo "有吗？？？ {{DOMAIN}}"
