---
  - name: copy kubelet
    copy:
      src: "{{kubelet}}"
      dest: "{{cmd_path}}/kubelet"
      mode: 0755
      backup: yes

  - name: copy kube-proxy
    copy:
      src: "{{kube_proxy}}"
      dest: "{{cmd_path}}/kube-proxy"
      mode: 0755
      backup: yes

  - name: copy kubeadm
    copy:
      src: "{{kubeadm}}"
      dest: "{{cmd_path}}/kubeadm"
      mode: 0755
      backup: yes

  - name: if not exists {{k8s_cfg_path}} else make
    file:
      path: "{{k8s_cfg_path}}"
      state: directory
      mode: 0755

  - name: copy kubelet config
    template:
      src: kubelet.conf.j2
      dest: "{{k8s_cfg_path}}/kubelet.conf"
      mode: 0644
      backup: yes

  - name: copy kube-proxy config
    template:
      src: kube-proxy.conf.j2
      dest: "{{k8s_cfg_path}}/kube-proxy.conf"
      mode: 0644
      backup: yes

  - name: copy kubelet service
    template:
      src: kubelet.service.j2
      dest: "{{service_path}}/kubelet.service"
      mode: 0644
      backup: yes

  - name: if not exists else make
    file:
      path: /var/lib/kubelet
      state: directory
      mode: 0755

  - name: restart kubelet
    service:
      name: kubelet.service
      state: restarted
    notify:
      - start kubelet

  - name: copy kube-proxy servier
    template:
      src: kube-proxy.service.j2
      dest: "{{service_path}}/kube-proxy.service"
      mode: 0644
      backup: yes

  - name: restart kube-proxy
    service:
      name: kube-proxy.service
      state: restarted
    notify:
    - start kube-proxy

