---
- name: start kube-apiserver
  service:
    name: kube-apiserver.service
    state: started
    enabled: yes

- name: start kube-controller-manager
  service:
    name: kube-controller-manager.service
    state: started
    enabled: yes

- name: start kube-scheduler
  service:
    name: kube-scheduler.service
    state: started
    enabled: yes
